# Info on the action
name: Automatic Publishing
run-name: ${{ github.actor }} is publishing 📸

on:
  # Run automatically on main pushes
  push:
    branches:
      - main
    paths:
      - 'shaders/**.glsl'
  # Or run on manual trigger
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'

env:
  TARGET_REPO: 'shadertoy-to-video'

jobs:
  # Gets all the different files
  getChanges:
    runs-on: ubuntu-latest
    # Return the files as outputs
    outputs:
      FILES: ${{ steps.prep.outputs.FILES }}
    steps:
      - name: 'Checking out code'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      # https://github.com/dorny/paths-filter
      # Look out for additions to the shaders
      - name: 'Getting the changes'
        id: changes
        uses: dorny/paths-filter@v2
        with:
          filters: |
            shaders:
              - added: 'shaders/**.glsl'
          initial-fetch-depth: 1
          list-files: 'json'
      - name: 'Prepare job outputs'
        id: prep
        run: |
          if [[ '${{steps.changes.outputs.shaders}}' -eq 'true' ]]; then
            echo "FILES=${{steps.changes.outputs.shaders_files}}" >> $GITHUB_OUTPUT
          else
            echo "Defaulting to no files..."
            echo "FILES=[]" >> $GITHUB_OUTPUT
          fi

  # Creates the different renders
  createRenders:
    runs-on: ubuntu-latest
    needs: getChanges
    # Will run once for each file
    strategy:
      matrix:
        shader: ${{ fromJSON(needs.getChanges.outputs.FILES) }}
    steps:
      - name: 'Checking out the code'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: 'Checking out the code for the library'
        uses: actions/checkout@v4
        with:
          repository: 'GonzaloHirsch/${{env.TARGET_REPO}}'
          fetch-depth: 0
      - name: 'Setting up Python'
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: 'Installing dependencies'
        run: pip install vispy watchdog glfw Pillow imageio PyQt5
      - name: 'Rendering the shader locally'
        run: |
          python3 ${{env.TARGET_REPO}}/shadertoy-render.py \
            --output ${{matrix.shader}}.mp4 --size=800x800 --rate=60 --bitrate=5M \
            --duration=30.0 ${{matrix.shader}}
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v3
        with:
          name: ${{matrix.shader}}
          path: ${{matrix.shader}}.mp4
          retention-days: 7

  # Renders uploaded have this URL schema https://tmpfiles.org/3436989/sun.png
  uploadRenders:
    runs-on: ubuntu-latest
    needs: [createRenders, getChanges]
    # Will run once for each file
    strategy:
      matrix:
        shader: ${{ fromJSON(needs.getChanges.outputs.FILES) }}
    # Outputs the different URLs
    outputs:
      URL: ${{ steps.upload.outputs.URL }}
    steps:
      - name: 'Download Artifacts'
        uses: actions/download-artifact@v3
        with:
          name: ${{matrix.shader}}
          path: ${{matrix.shader}}.mp4
      - name: 'Upload to temporary server'
        id: upload
        run: |
          RESPONSE=$(curl -F "file=@${{matrix.shader}}.mp4" https://tmpfiles.org/api/v1/upload)
          echo "Response from the temporary fileserver is $RESPONSE"
          URL=$(echo $RESPONSE | jq -r ".data.url")
          echo "URL=$URL" >> $GITHUB_OUTPUT

  # Notify for renders
  notifyWithEmail:
    runs-on: ubuntu-latest
    needs: uploadRenders
    # Will run once for each generated URL
    strategy:
      matrix:
        url: ${{ fromJSON(needs.uploadRenders.outputs.URL) }}
    steps:
      # Update with version if release
      - name: 'Configure AWS Credentials'
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      # Prepare to send email
      - name: 'Prepare email payload'
        run: |
          export FILENAME_BASE=$(openssl rand -base64 12)
          export FILENAME="${FILENAME_BASE}_message.json"
          echo "{\"Data\": \"From: ${{secrets.EMAIL_FROM}}\nTo: ${{secrets.EMAIL_TO}}\nSubject: [${{secrets.IG_ACCOUNT}}] New Post \nMIME-Version: 1.0\nContent-type: Multipart/Mixed; boundary=\\\"NextPart\\\"\n\n--NextPart\nContent-Type: text/plain\n\nYou can find the render for the post in here ${{matrix.url}}\n\n--NextPart--\"}" > $FILENAME
      # Send the actual email
      - name: 'Send email payload'
        run: |
          aws ses send-raw-email --region ${{ secrets.AWS_REGION }} --tags Name=app,Value=appshaders.gonzalohirsch.com --cli-binary-format raw-in-base64-out --raw-message file://$FILENAME
